Section "Monitor"
    Identifier "HDMI-A-2"
    Option "Primary" "true"
    Option "Rotate" "normal"
EndSection

Section "Monitor"
    Identifier "HDMI-A-1"
    Option "Rotate" "left"
    Option "LeftOf" "HDMI-A-2"
EndSection
