[General]
x=0
y=0

[caching]
lastCacheFileHash=@ByteArray(bc8c7d739a7f6c107f1a2578913328f55f82eab861d20b2d40d686bf566361db)
lastDownloadSHA256=@ByteArray(9fb9d80b9e2bcd765baccdf926bba9d5a57c43b671e1a3c74eb5ab7d09744f7f)
lastFileName=/home/bryan/.cache/Raspberry Pi/Imager/lastdownload.cache

[imagecustomization]
sshEnabled=true
sshUserName=pi
sshUserPassword=$5$ytRtUH/.wv$DNMcNI.KxEnTd0IMnG3Q28YykJI3S2kWQvjVGS/a/A1
